version: '3.9'

volumes:
  redis_data:
    driver: local
  pgdata:
    driver: local


services:

  pgadmin:
    container_name: pgadmin-not
    restart: always
    image: dpage/pgadmin4:6.19
    expose:
      - 80
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    depends_on:
      - postgres

  postgres:
    container_name: bd-not
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    container_name: redis-not
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/bitnami/redis/data'
