# Generated by Django 4.2.5 on 2023-09-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
